### ISSUE TITLE
Getting "No ffmpeg exe could be found" even though I have ffpmeg installed

### ISSUE THREAD

**Issue by zeke** [cbh123/youtune#9]
```
$ python tune.py "https://www.youtube.com/watch?v=UcmFu_Mcf_Q"
Traceback (most recent call last):
  File "/Users/z/Desktop/youtune/tune.py", line 2, in <module>
    from moviepy.editor import AudioFileClip
  File "/Users/z/.pyenv/versions/python-3.10.4/lib/python3.10/site-packages/moviepy/editor.py", line 36, in <module>
    from .video.io.VideoFileClip import VideoFileClip
  File "/Users/z/.pyenv/versions/python-3.10.4/lib/python3.10/site-packages/moviepy/video/io/VideoFileClip.py", line 3, in <module>
    from moviepy.audio.io.AudioFileClip import AudioFileClip
  File "/Users/z/.pyenv/versions/python-3.10.4/lib/python3.10/site-packages/moviepy/audio/io/AudioFileClip.py", line 3, in <module>
    from moviepy.audio.AudioClip import AudioClip
  File "/Users/z/.pyenv/versions/python-3.10.4/lib/python3.10/site-packages/moviepy/audio/AudioClip.py", line 7, in <module>
    from moviepy.audio.io.ffmpeg_audiowriter import ffmpeg_audiowrite
  File "/Users/z/.pyenv/versions/python-3.10.4/lib/python3.10/site-packages/moviepy/audio/io/ffmpeg_audiowriter.py", line 7, in <module>
    from moviepy.config import get_setting
  File "/Users/z/.pyenv/versions/python-3.10.4/lib/python3.10/site-packages/moviepy/config.py", line 36, in <module>
    FFMPEG_BINARY = get_exe()
  File "/Users/z/.pyenv/versions/python-3.10.4/lib/python3.10/site-packages/imageio/plugins/ffmpeg.py", line 173, in get_exe
    return imageio_ffmpeg.get_ffmpeg_exe()
  File "/Users/z/.pyenv/versions/python-3.10.4/lib/python3.10/site-packages/imageio_ffmpeg/_utils.py", line 34, in get_ffmpeg_exe
    raise RuntimeError(
RuntimeError: No ffmpeg exe could be found. Install ffmpeg on your system, or set the IMAGEIO_FFMPEG_EXE environment variable.

~/Desktop/youtune main
$ which ffmpeg
/opt/homebrew/bin/ffmpeg
```

cc @cbh123

**Comment by cbh123** [comment]
Thanks @zeke I will investigate. Just confirming, this is within the virtual env and after installing dependencies?

```
python3 -m pip install virtualenv
python3 -m virtualenv venv
source venv/bin/activate
pip install -r requirements.txt
```

**Comment by zeke** [comment]
Oh forgot to follow up it was me. My FFMPEG installation was hosed. Brew uninstalled, reinstalled, and all is well. 😅
